# Homework 7

### Question 3c

In [1]:
import pandas as pd
import numpy as np
from scipy import linalg

In [2]:
A = np.array([[1,1,1,0,0], [-2,1,0,1,0], [2,1,0,0,1]])
b = np.array([[4],[2],[6]])
c = np.array([[-1],[-2],[0],[0],[0]])

In [3]:
combos = [[0,1,2], [0,1,3], [0,1,4], [0,2,3], [0,2,4], [0,3,4], [1,2,3], [1,2,4], [1,3,4], [2,3,4]]
anti_combo = [[3,4], [2,4], [2,3], [1,4], [1,3], [1,2], [0,4], [0,3], [0,2], [0,1]]

In [4]:
for i in range(len(combos)):
    
    # Slice A into B and N based on combinations of 3 vectors
    B_index = combos[i]
    N_index = anti_combo[i]
    B = A[:,B_index]
    N = A[:,N_index]
    
    print("Basis Matrix: " + str(["A_" + str(x+1) for x in B_index]))
    print(B)
    
    # Calculate x_B, x_N, c_B, c_N
    B_inv = linalg.inv(B)
    x_B = B_inv@b
    c_B = c[B_index]
    x_N = np.array([[0],[0]])
    c_N = c[N_index]
    
    # Create full x variable based on indicies of current combination
    d = {}
    for i in range(0,len(B_index)):
        d[B_index[i]] = x_B[i][0]
    for i in range(0,len(N_index)):
        d[N_index[i]] = x_N[i][0]
    
    x = []
    for key in sorted(d.keys()):
        x.append(d[key])
    
    # Calculate objective value 
    obj_value = c.transpose()@np.array(x)

    print("Basic Variables: x_B = " + str(x_B.transpose()) + "^T")
    print("Cost Coefficients of Basic Variables: c_B = " + str(c_B.transpose()) + "^T")
    print("Non-Basic Variables: x_N = " + str(x_N.transpose()) + "^T")
    print("Cost Coefficients of Non-Basic Variables: c_N = " + str(c_N.transpose()) + "^T")
    print("x = " + str(x))
    print("Objective Value = " + str(obj_value[0]))
    print("")

Basis Matrix: ['A_1', 'A_2', 'A_3']
[[ 1  1  1]
 [-2  1  0]
 [ 2  1  0]]
Basic Variables: x_B = [[ 1.  4. -1.]]^T
Cost Coefficients of Basic Variables: c_B = [[-1 -2  0]]^T
Non-Basic Variables: x_N = [[0 0]]^T
Cost Coefficients of Non-Basic Variables: c_N = [[0 0]]^T
x = [1.0, 4.0, -1.0, 0, 0]
Objective Value = -9.0

Basis Matrix: ['A_1', 'A_2', 'A_4']
[[ 1  1  0]
 [-2  1  1]
 [ 2  1  0]]
Basic Variables: x_B = [[2. 2. 4.]]^T
Cost Coefficients of Basic Variables: c_B = [[-1 -2  0]]^T
Non-Basic Variables: x_N = [[0 0]]^T
Cost Coefficients of Non-Basic Variables: c_N = [[0 0]]^T
x = [2.0, 2.0, 0, 4.0, 0]
Objective Value = -6.0

Basis Matrix: ['A_1', 'A_2', 'A_5']
[[ 1  1  0]
 [-2  1  0]
 [ 2  1  1]]
Basic Variables: x_B = [[0.66666667 3.33333333 1.33333333]]^T
Cost Coefficients of Basic Variables: c_B = [[-1 -2  0]]^T
Non-Basic Variables: x_N = [[0 0]]^T
Cost Coefficients of Non-Basic Variables: c_N = [[0 0]]^T
x = [0.6666666666666666, 3.333333333333333, 0, 0, 1.333333333333334]
Objectiv