# Homework 8 
### Question 3

In [1]:
import pandas as pd
import numpy as np
from scipy import linalg

In [2]:
A = np.array([[1,1,1,0,0], [-1,1,0,1,0], [1,-1,0,0,1]])
b = np.array([[4],[2],[2]])
c = np.array([[-2],[4],[0],[0],[0]])

In [3]:
# for i in range(1):
#     print("Iteration: " + str(i+1))
    
#     # Slice A into B and N based on combinations of 3 vectors
# #     B_index = combos[i]
# #     N_index = anti_combo[i]

def get_info(A, b, c, bfs, nbfs):
    B = A[:,bfs]
    N = A[:,nbfs]
    
    print("Basis Matrix: ")
    print(B)
    
    print("Inverse Basis Matrix:")
    B_inv = linalg.inv(B)
    print(B_inv)
    
    print("Basic Variables: "+ str(["x_" + str(x+1) for x in bfs]))
    x_B = B_inv@b
    print(x_B)
    
    print("Non-Basic Variables: "+ str(["x_" + str(x+1) for x in nbfs]))
    x_N = np.array([[0],[0]])
    print(x_N)
    
    c_bfs = c[bfs]
    
    c_first_red = c[nbfs[0]] - c_bfs.T@B_inv@A[:,nbfs[0]]
    c_second_red = c[nbfs[1]] - c_bfs.T@B_inv@A[:,nbfs[1]]
        
    print("Reduced Cost for c_" + str(nbfs[0]+1) + " = " + str(c_first_red))
    print(c[nbfs[0]], c_bfs.T@B_inv@A[:,nbfs[0]])
    print("Reduced Cost for c_" + str(nbfs[1]+1) + " = " + str(c_second_red))  
    print(c[nbfs[1]], c_bfs.T@B_inv@A[:,nbfs[1]])
    
    if ((c_first_red < 0) and (c_second_red > 0)):
        enter_index = nbfs[0]
    elif ((c_first_red > 0) and (c_second_red < 0)):
        enter_index = nbfs[1]
    else:
        enter_index = min(nbfs)
   
    print("Enters Basis: x_" + str(enter_index + 1))
    print("Direction:")
    d_B = -B_inv@A[:,enter_index]
    print(d_B)
    
    return None

In [4]:
# Iteration 1
bfs = [0,1,4]
nbfs = [2,3]
get_info(A, b, c, bfs, nbfs)

Basis Matrix: 
[[ 1  1  0]
 [-1  1  0]
 [ 1 -1  1]]
Inverse Basis Matrix:
[[ 0.5 -0.5 -0. ]
 [ 0.5  0.5 -0. ]
 [ 0.   1.   1. ]]
Basic Variables: ['x_1', 'x_2', 'x_5']
[[1.]
 [3.]
 [4.]]
Non-Basic Variables: ['x_3', 'x_4']
[[0]
 [0]]
Reduced Cost for c_3 = [-1.]
[0] [1.]
Reduced Cost for c_4 = [-3.]
[0] [3.]
Enters Basis: x_3
Direction:
[-0.5 -0.5  0. ]


In [5]:
# Iteration 2
bfs = [1,2,4]
nbfs = [0,3]
get_info(A, b, c, bfs, nbfs)

Basis Matrix: 
[[ 1  1  0]
 [ 1  0  0]
 [-1  0  1]]
Inverse Basis Matrix:
[[ 0.  1. -0.]
 [ 1. -1.  0.]
 [ 0.  1.  1.]]
Basic Variables: ['x_2', 'x_3', 'x_5']
[[2.]
 [2.]
 [4.]]
Non-Basic Variables: ['x_1', 'x_4']
[[0]
 [0]]
Reduced Cost for c_1 = [2.]
[-2] [-4.]
Reduced Cost for c_4 = [-4.]
[0] [4.]
Enters Basis: x_4
Direction:
[-1.  1. -1.]


In [6]:
# Iteration 3
bfs = [1,3,4]
nbfs = [0,2]
get_info(A, b, c, bfs, nbfs)

Basis Matrix: 
[[ 1  0  0]
 [ 1  1  0]
 [-1  0  1]]
Inverse Basis Matrix:
[[ 1. -0. -0.]
 [-1.  1. -0.]
 [ 1.  0.  1.]]
Basic Variables: ['x_2', 'x_4', 'x_5']
[[ 4.]
 [-2.]
 [ 6.]]
Non-Basic Variables: ['x_1', 'x_3']
[[0]
 [0]]
Reduced Cost for c_1 = [-6.]
[-2] [4.]
Reduced Cost for c_3 = [-4.]
[0] [4.]
Enters Basis: x_1
Direction:
[-1.  2. -2.]


In [8]:
# Iteration 3
bfs = [0,1,3]
nbfs = [2,4]
get_info(A, b, c, bfs, nbfs)

Basis Matrix: 
[[ 1  1  0]
 [-1  1  1]
 [ 1 -1  0]]
Inverse Basis Matrix:
[[ 0.5  0.   0.5]
 [ 0.5  0.  -0.5]
 [ 0.   1.   1. ]]
Basic Variables: ['x_1', 'x_2', 'x_4']
[[3.]
 [1.]
 [4.]]
Non-Basic Variables: ['x_3', 'x_5']
[[0]
 [0]]
Reduced Cost for c_3 = [-1.]
[0] [1.]
Reduced Cost for c_5 = [3.]
[0] [-3.]
Enters Basis: x_3
Direction:
[-0.5 -0.5  0. ]
